# Generated by Django 6.1.1 on 2026-10-06 07:51

import django.db.models.deletion
import django.utils.timezone
from datetime import datetime, timezone
from decimal import Decimal
from django.db import migrations, models


def load_dump_sample_data(apps, schema_editor):
    DiagnosticSymptom = apps.get_model('motor', 'DiagnosticSymptom')
    TroubleshootingGuide = apps.get_model('motor', 'TroubleshootingGuide')
    Part = apps.get_model('motor', 'Part')
    GuideRequiredPart = apps.get_model('motor', 'GuideRequiredPart')
    created_at = datetime(2026, 10, 6, 1, 45, 19, tzinfo=timezone.utc)

    DiagnosticSymptom.objects.using(schema_editor.connection.alias).create(
        id=1,
        symptom_name='Smoke near engine and front sprocket',
        category='Engine',
        description='White or gray smoke issuing near the front sprocket area after riding.',
        created_at=created_at,
    )
    Part.objects.using(schema_editor.connection.alias).create(
        id=1,
        part_name='Front Sprocket Oil Seal',
        part_number='OS-17-29-6',
        category='Engine Seals',
        estimated_cost=Decimal('150.00'),
        created_at=created_at,
    )
    TroubleshootingGuide.objects.using(schema_editor.connection.alias).create(
        id=1,
        symptom_id=1,
        possible_cause='Leaking front sprocket oil seal dripping onto hot engine casing/exhaust',
        repair_instructions=(
            '1. Remove shift lever and sprocket cover.\n'
            '2. Clean oil grime using engine degreaser.\n'
            '3. Remove chain and front sprocket.\n'
            '4. Pry out damaged oil seal carefully.\n'
            '5. Install new oil seal flush with casing.\n'
            '6. Reassemble sprocket and chain.'
        ),
        advice_notes='Check engine oil level immediately to prevent engine starvation.',
        created_at=created_at,
    )
    GuideRequiredPart.objects.using(schema_editor.connection.alias).create(
        id=1,
        guide_id=1,
        part_id=1,
        quantity_needed=1,
    )


def remove_dump_sample_data(apps, schema_editor):
    GuideRequiredPart = apps.get_model('motor', 'GuideRequiredPart')
    TroubleshootingGuide = apps.get_model('motor', 'TroubleshootingGuide')
    Part = apps.get_model('motor', 'Part')
    DiagnosticSymptom = apps.get_model('motor', 'DiagnosticSymptom')
    db_alias = schema_editor.connection.alias

    GuideRequiredPart.objects.using(db_alias).filter(pk=1).delete()
    TroubleshootingGuide.objects.using(db_alias).filter(pk=1).delete()
    Part.objects.using(db_alias).filter(pk=1).delete()
    DiagnosticSymptom.objects.using(db_alias).filter(pk=1).delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticSymptom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symptom_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'diagnostic_symptoms',
            },
        ),
        migrations.CreateModel(
            name='MotorAssistantUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('role', models.CharField(blank=True, default='Mechanic', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'parts',
            },
        ),
        migrations.CreateModel(
            name='TroubleshootingGuide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('possible_cause', models.CharField(max_length=255)),
                ('repair_instructions', models.TextField()),
                ('advice_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshooting_guides', to='motor.diagnosticsymptom')),
            ],
            options={
                'db_table': 'troubleshooting_guides',
            },
        ),
        migrations.CreateModel(
            name='GuideRequiredPart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_needed', models.IntegerField(default=1, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_requirements', to='motor.part')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_parts', to='motor.troubleshootingguide')),
            ],
            options={
                'db_table': 'guide_required_parts',
            },
        ),
        migrations.RunPython(load_dump_sample_data, remove_dump_sample_data),
    ]
